# Generated by Django 6.0.6 on 2026-09-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('author', models.CharField(default='S_Cart Editorial', max_length=100)),
                ('author_role', models.CharField(blank=True, default='Senior Tech & Lifestyle Editor', max_length=100)),
                ('author_avatar', models.CharField(default='A', max_length=10)),
                ('category', models.CharField(default='Technology', max_length=100)),
                ('tags', models.CharField(default='Tech, Shopping', max_length=200)),
                ('read_time', models.CharField(default='5 min', max_length=50)),
                ('excerpt', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='blog/images')),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=500)),
                ('icon', models.CharField(default='📱', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
        ),
    ]
